#!/usr/bin/env bash

# We prepare the ROOT filesystem with dependencies from NPM
# Since there is no functional NPM on the system yet, we use NPM from the
# downloaded Node.js source code to install NPM packages into the container

set -o pipefail


GRN="\e[32m"
CLR="\e[0m"


__dirname=`dirname "$(readlink -f "$0")"`


while getopts ":B:F:I:K:O:U:" opt; do
  case $opt in
    B)
      BAREBONES="$OPTARG"  # Location of the barebones image
    ;;

    F)
      FORMAT="$OPTARG"  # Output format
    ;;

    I)
      INITRAMFS="$OPTARG"  # Location of the initramfs image
    ;;

    K)
      KERNEL="$OPTARG"  # Location of the barebones kernel
    ;;

    O)
      OUTPUT="$OPTARG"  # Output location
    ;;

    U)
      USERSFS="$OPTARG"  # Usersfs location to be mounted from
    ;;
  esac
done

if [[ -z "$OUTPUT" ]]; then
  echo "-O is mandatory"
  exit 1
fi

if [[ "$USERSFS" ]]; then
  USERSFS=`blkid $USERSFS -o export | grep UUID`
fi


TOOLCHAIN=`node -p "require('nodeos-cross-toolchain')"`

source $TOOLCHAIN/scripts/adjustEnvVars.sh || exit $?


if [[ -d $OBJECTS ]]; then
  chmod -R u+w $OBJECTS &&
  rm    -rf    $OBJECTS || exit 10
fi


#
# Define steps paths
#

EFIBOOT_DIR=$OBJECTS/efiboot
EFIBOOT_IMG=$EFIBOOT_DIR.img
IMG_DIR=$OBJECTS/img
ISO_DIR=$OBJECTS/iso


#
# SysLinux
#

SRC_DIR=$__dirname/../deps/syslinux


#
# Wrap the system up and pack it
#

function createPartitionImage() {
  # Copy kernel and initramfs on the partition image

  cp $KERNEL    $STEP_DIR/kernel.img &&
  cp $INITRAMFS $STEP_DIR/initram.gz || exit 20

  # Create partition image

  mkdir -p `dirname $OUTPUT` || exit 21

  # Size in KB
  # DISK_SIZE=`du -ks $STEP_DIR | cut -f1`
  DISK_SIZE=$((20*1024))

  genfatfs -b $DISK_SIZE \
      --root $STEP_DIR   \
      $OUTPUT            || exit 22
}

function createEfiImage() {
  STEP_DIR=$EFIBOOT_DIR

  rm -rf $STEP_DIR   &&
  mkdir -p $STEP_DIR || exit 30

  # Copy SysLinux files

  eval "echo \"(<$__dirname/../resources/syslinux.cfg)\"" > $STEP_DIR || exit 31

  cp $SRC_DIR/efi$BITS/efi/syslinux.efi                     \
     $SRC_DIR/efi$BITS/com32/elflink/ldlinux/ldlinux.e$BITS \
     $STEP_DIR                                              || exit 32

  # Copy kernel and initramfs on the ISO image

  cp $KERNEL    $STEP_DIR/kernel.img &&
  cp $INITRAMFS $STEP_DIR/initram.gz || exit 33

  # Create EFI disk image

  # DISK_SIZE=`du -ks $STEP_DIR | cut -f1`
  DISK_SIZE=$((20*1024))

  genfatfs -b $DISK_SIZE \
    --root $STEP_DIR     \
    $EFIBOOT_IMG         || exit 34
}

function createIsoImage() {
  mkdir -p                                                  $STEP_DIR &&
  eval "echo \"(<$__dirname/../resources/syslinux.cfg)\"" > $STEP_DIR || exit 40

  # Create EFI boot image
  createEfiImage            || exit $?
  cp $EFIBOOT_IMG $STEP_DIR || exit 41

  # Copy IsoLinux files

  cp $SRC_DIR/bios/core/isolinux.bin                 \
     $SRC_DIR/bios/com32/elflink/ldlinux/ldlinux.c32 \
     $STEP_DIR                                       || exit 42

  # Copy kernel and initramfs on the ISO image

  cp $KERNEL    $STEP_DIR/kernel.img &&
  cp $INITRAMFS $STEP_DIR/initram.gz || exit 43

  # Create ISO image

  mkdir -p `dirname $OUTPUT` || exit 44

  # http://wiki.osdev.org/Bootable_El-Torito_CD_with_GRUB_Legacy#Mkisofs_says_Uh_oh.2C_I_cant_find_the_boot_image
  # genisoimage looks for its boot image as a subdirectory of the filesystem on the CD
  genisoimage -o $OUTPUT  \
    -c boot.cat           \
    -V NodeOS             \
    -b isolinux.bin       \
      -no-emul-boot       \
      -boot-load-size 4   \
      -boot-info-table    \
    -eltorito-alt-boot    \
    -efi-boot efiboot.img \
      -no-emul-boot       \
    $STEP_DIR             || exit 45

  $SRC_DIR/bios/utils/isohybrid $OUTPUT || exit 46
}


case $MACHINE in
  pc)
    case $FORMAT in
      img)  # FAT partition
        STEP_DIR=$IMG_DIR

        mkdir -p $STEP_DIR || err 70

        # Copy SysLinux files

        eval "echo \"(<$__dirname/../resources/syslinux.cfg)\"" > $STEP_DIR || exit 71

        createPartitionImage || exit $?

        $SRC_DIR/bios/mtools/syslinux --install $OUTPUT || exit 72
      ;;

      iso)  # Hybrid ISO image for CDs and USB pendrives
        STEP_DIR=$ISO_DIR

        createIsoImage || exit $?
      ;;

      tar)  # Combine both barebones and initramfs tarfiles in a single one
        STEP_DIR=$OUTPUT

        mkdir -p `dirname $STEP_DIR` || err 80

        gunzip $BAREBONES -c | tar --delete init | gzip > $STEP_DIR &&
        cat    $INITRAMFS                              >> $STEP_DIR || err 81
      ;;

      *)
        echo -e "${RED}Unknown FORMAT '$FORMAT'${CLR}"
        exit 90
      ;;
    esac
  ;;

  raspi|raspi2|raspi3)  # FAT partition for Raspberry PI
    case $FORMAT in
      img)
        STEP_DIR=$IMG_DIR

        mkdir -p $STEP_DIR || err 100

        # Copy Raspberry PI extra files
        # http://elinux.org/RPi_Advanced_Setup#Setting_up_the_boot_partition
        #
        # bootcode.bin, start.elf, cmdline.txt
        (
          cd $STEP_DIR || exit 101

          wget https://github.com/raspberrypi/firmware/raw/master/boot/bootcode.bin || exit 102
          wget https://github.com/raspberrypi/firmware/raw/master/boot/start.elf    || exit 103
        ) || err $?

        createPartitionImage || exit $?
      ;;

      *)
        echo -e "${RED}Unknown FORMAT '$FORMAT'${CLR}"
        exit 110
      ;;
    esac
  ;;

  *)
    echo -e "${RED}Unknown MACHINE '$MACHINE'${CLR}"
    exit 120
  ;;
esac


echo -e "${GRN}Successfully built 'bootfs'${CLR}"
