#!/usr/bin/env bash

# We prepare the ROOT filesystem with dependencies from NPM
# Since there is no functional NPM on the system yet, we use NPM from the
# downloaded Node.js source code to install NPM packages into the container

set -o pipefail


GRN="\e[32m"
CLR="\e[0m"


__dirname=`dirname "$(readlink -f "$0")"`


while getopts ":B:D:F:I:K:O:U:" opt; do
  case $opt in
    B)
      BAREBONES="$OPTARG"  # Location of the barebones image
    ;;

    D)
      DTS="$OPTARG"  # Device Tree Specs directory
    ;;

    F)
      FORMAT="$OPTARG"  # Output format
    ;;

    I)
      INITRAMFS="$OPTARG"  # Location of the initramfs image
    ;;

    K)
      KERNEL="$OPTARG"  # Location of the barebones kernel
    ;;

    O)
      OUTPUT="$OPTARG"  # Output location
    ;;

    U)
      USERSFS="$OPTARG"  # Usersfs location to be mounted from
    ;;
  esac
done

if [[ -z "$OUTPUT" ]]; then
  echo "-O is mandatory"
  exit 1
fi

if [[ "$USERSFS" ]]; then
  USERSFS_UUID=`blkid $USERSFS -o export | grep UUID`
fi


TOOLCHAIN=`node -p "require('nodeos-cross-toolchain')"`

source $TOOLCHAIN/scripts/adjustEnvVars.sh || exit $?


if [[ -d $OBJECTS ]]; then
  chmod -R u+w $OBJECTS &&
  rm    -rf    $OBJECTS || exit 2
fi


#
# Define steps paths
#

EFIBOOT_DIR=$OBJECTS/efiboot
EFIBOOT_IMG=$EFIBOOT_DIR.img
DISK_DIR=$OBJECTS/disk
IMG_DIR=$OBJECTS/img
ISO_DIR=$OBJECTS/iso


#
# SysLinux
#

SRC_DIR=$__dirname/../deps/syslinux


#
# Wrap the system up and pack it
#

# Disk images are a composition of bootfs and usersfs
function createDiskImage() {
  BOOTFS=$1

  STEP_DIR=$DISK_DIR

  # ToDo: sizes would need to be on cylinders and retain DOS compatibility
  # http://elinux.org/RPi_Advanced_Setup#Advanced_SD_card_setup

  SIZE_MBR=$((2*1024))  # Reserve first megabyte for raspi. Is this needed?
  SIZE_BOOTFS=$(stat -L -c%s "$BOOTFS")
  SIZE_BOOTFS=$(($SIZE_BOOTFS/512))
  START_USERSFS=$(($SIZE_MBR+$SIZE_BOOTFS))

  dd if=/dev/zero of=$OUTPUT count=$SIZE_MBR     &&
  dd if=$BOOTFS   of=$OUTPUT seek=$SIZE_MBR      &&
  dd if=$USERSFS  of=$OUTPUT seek=$START_USERSFS || exit 10

  eval "echo \"$(<$__dirname/../resources/sfdisk.txt)\"" | \
      /sbin/sfdisk -uS --force $OUTPUT                   || exit 11
}

function createPartitionImage() {
  BOOTFS=$1

  # Copy kernel and initramfs on the partition image

  cp $INITRAMFS $STEP_DIR/initram.gz || exit 20

  # Create partition image

  mkdir -p `dirname $BOOTFS` || exit 21

  # Size in KB
  # DISK_SIZE=`du -ks $STEP_DIR | cut -f1`
  DISK_SIZE=$((32*1024))

  genfatfs -b $DISK_SIZE \
      --root $STEP_DIR   \
      $BOOTFS            || exit 22
}

function createEfiImage() {
  STEP_DIR=$EFIBOOT_DIR

  rm -rf $STEP_DIR   &&
  mkdir -p $STEP_DIR || exit 30

  # Copy SysLinux files

  eval "echo \"$(<$__dirname/../resources/syslinux.cfg)\"" \
      > $STEP_DIR/syslinux.cfg                             || exit 31

  cp $SRC_DIR/efi$BITS/efi/syslinux.efi                     \
     $SRC_DIR/efi$BITS/com32/elflink/ldlinux/ldlinux.e$BITS \
     $STEP_DIR                                              || exit 32

  # Copy kernel and initramfs on the ISO image

  cp $KERNEL    $STEP_DIR &&
  cp $INITRAMFS $STEP_DIR/initram.gz || exit 33

  # Create EFI disk image

  # DISK_SIZE=`du -ks $STEP_DIR | cut -f1`
  DISK_SIZE=$((32*1024))

  genfatfs -b $DISK_SIZE \
    --root $STEP_DIR     \
    $EFIBOOT_IMG         || exit 34
}

function createIsoImage() {
  STEP_DIR=$ISO_DIR

  mkdir -p $STEP_DIR || exit 40

  eval "echo \"$(<$__dirname/../resources/syslinux.cfg)\"" \
      > $STEP_DIR/syslinux.cfg                             || exit 41

  # Create EFI boot image
  createEfiImage            || exit $?
  cp $EFIBOOT_IMG $STEP_DIR || exit 42

  # Copy IsoLinux files

  cp $SRC_DIR/bios/core/isolinux.bin                 \
     $SRC_DIR/bios/com32/elflink/ldlinux/ldlinux.c32 \
     $STEP_DIR                                       || exit 43

  # Copy kernel and initramfs on the ISO image

  cp $KERNEL    $STEP_DIR &&
  cp $INITRAMFS $STEP_DIR/initram.gz || exit 44

  # Create ISO image

  mkdir -p `dirname $OUTPUT` || exit 45

  # http://wiki.osdev.org/Bootable_El-Torito_CD_with_GRUB_Legacy#Mkisofs_says_Uh_oh.2C_I_cant_find_the_boot_image
  # genisoimage looks for its boot image as a subdirectory of the filesystem on the CD
  genisoimage -o $OUTPUT  \
    -c boot.cat           \
    -V NodeOS             \
    -b isolinux.bin       \
      -no-emul-boot       \
      -boot-load-size 4   \
      -boot-info-table    \
    -eltorito-alt-boot    \
    -efi-boot efiboot.img \
      -no-emul-boot       \
    $STEP_DIR             || exit 46

  $SRC_DIR/bios/utils/isohybrid $OUTPUT || exit 47
}

function createTar() {
  STEP_DIR=$OUTPUT

  mkdir -p `dirname $STEP_DIR` || err 50

  gunzip $BAREBONES -c | tar --delete init | gzip > $STEP_DIR &&
  cat    $INITRAMFS                              >> $STEP_DIR || err 51
}


function img_pc() {
  STEP_DIR=$IMG_DIR

  mkdir -p $STEP_DIR || err 60

  BOOTFS=$1

  # Copy SysLinux files

  eval "echo \"$(<$__dirname/../resources/syslinux.cfg)\"" \
      > $STEP_DIR/syslinux.cfg                             || exit 61

  cp $KERNEL $STEP_DIR || exit 62

  createPartitionImage $BOOTFS || exit $?

  $SRC_DIR/bios/mtools/syslinux --install $BOOTFS || exit 63
}

function img_raspi() {
  STEP_DIR=$IMG_DIR

  mkdir -p $STEP_DIR || err 70

  BOOTFS=$1

  # Copy Raspberry PI extra files
  # http://elinux.org/RPi_Advanced_Setup#Setting_up_the_boot_partition
  #
  # bootcode.bin, fixup.dat, start.elf, cmdline.txt
  (
    cd $STEP_DIR || exit 71

    wget https://github.com/raspberrypi/firmware/raw/master/boot/bootcode.bin || exit 72
    wget https://github.com/raspberrypi/firmware/raw/master/boot/fixup.dat    || exit 73
    wget https://github.com/raspberrypi/firmware/raw/master/boot/start.elf    || exit 74
  ) || err $?

  cp $__dirname/../resources/config.txt $DTS $STEP_DIR || exit 75

  case $MACHINE in
    raspi)
      cp $KERNEL $STEP_DIR/kernel.img || exit 76
    ;;

    raspi2)
      cp $KERNEL $STEP_DIR/kernel7.img || exit 77
    ;;

    raspi3)
      echo arm_control=0x200 >> $STEP_DIR/config.txt &&
      cp $KERNEL $STEP_DIR/kernel7.img               || exit 78
    ;;

    *)
      echo -e "${RED}Unknown MACHINE '$MACHINE'${CLR}"
      exit 79
    ;;
  esac

  createPartitionImage $BOOTFS || exit $?
}


case $MACHINE in
  pc)
    case $FORMAT in
      disk)
        if [[ -z "$USERSFS" ]]; then
          echo "-U is mandatory"
          exit 80
        fi

        BOOTFS=$DISK_DIR/bootfs.img

        img_pc          $BOOTFS &&
        createDiskImage $BOOTFS || exit $?

        dd bs=440 count=1 conv=notrunc              \
            if=$SRC_DIR/bios/mbr/mbr.bin of=$OUTPUT || err 81
      ;;

      img)  # FAT partition
        img_pc $OUTPUT || exit $?
      ;;

      iso)  # Hybrid ISO image for CDs and USB pendrives
        createIsoImage || exit $?
      ;;

      tar)  # Combine both barebones and initramfs tarfiles in a single one
        createTar || exit $?
      ;;

      *)
        echo -e "${RED}Unknown FORMAT '$FORMAT'${CLR}"
        exit 90
      ;;
    esac
  ;;

  raspi|raspi2|raspi3)  # FAT partition for Raspberry PI
    if [[ -z "$DTS" ]]; then
      echo "-D is mandatory for MACHINE '$MACHINE'"
      exit 100
    fi

    case $FORMAT in
      disk)
        if [[ -z "$USERSFS" ]]; then
          echo "-U is mandatory"
          exit 110
        fi

        BOOTFS=$DISK_DIR/bootfs.img

        img_raspi       $BOOTFS &&
        createDiskImage $BOOTFS || exit $?
      ;;

      img)
        img_raspi $OUTPUT || exit $?
      ;;

      *)
        echo -e "${RED}Unknown FORMAT '$FORMAT'${CLR}"
        exit 120
      ;;
    esac
  ;;

  *)
    echo -e "${RED}Unknown MACHINE '$MACHINE'${CLR}"
    exit 130
  ;;
esac


echo -e "${GRN}Successfully built 'bootfs'${CLR}"
